package com.example.demo.news;

import jakarta.persistence.*;

@Entity
@Table(name = "news_main")
public class NewsDetails {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id; // autogenerated ID

    private String source;
    private String author;
    @Column(length =  10000)
    private String title;
    
    @Column(columnDefinition = "TEXT") // Use TEXT data type for large text data
    private String description;

    @Column(columnDefinition = "TEXT")
    private String url;

    @Column(columnDefinition = "TEXT")// Use TEXT data type for large text data
    private String img_url;

    private String publishedAt; // Changed the attribute name to match the JSON field name

    @Column(columnDefinition = "TEXT") // Use TEXT data type for large text data
    private String content;

    private long likes = 0;
    private boolean isSaved = false;

    

    public NewsDetails(long id, String source, String author, String title, String description, String url,
            String img_url, String publishedAt, String content, long likes, boolean isSaved) {
        this.id = id;
        this.source = source;
        this.author = author;
        this.title = title;
        this.description = description;
        this.url = url;
        this.img_url = img_url;
        this.publishedAt = publishedAt;
        this.content = content;
        this.likes = likes;
        this.isSaved = isSaved;
    }

    public NewsDetails() {
    }

    // Getters and setters...
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImg_url() {
        return img_url;
    }

    public void setImg_url(String img_url) {
        this.img_url = img_url;
    }

    public String getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public long getLikes() {
        return likes;
    }

    public void setLikes(long likes) {
        this.likes = likes;
    }

    public boolean isSaved() {
        return isSaved;
    }

    public void setSaved(boolean isSaved) {
        this.isSaved = isSaved;
    }
}
